[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
address = "0.0.0.0"
port = 8501

[theme]
base = "dark"
primaryColor = "#00E676"
backgroundColor = "#050807"
secondaryBackgroundColor = "#080D0A"
textColor = "#FFFFFF"
font = "sans serif"
